{{- include "adp-helm-library.deployment" (list . "frontend-manual-testing-external-ui.deployment") -}}
{{- define "frontend-manual-testing-external-ui.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "adp-helm-library.container" (list . "frontend-manual-testing-external-ui.container") }}
{{- end -}}
